// src/data/properties.js

export const properties = [
  {
    id: 1,
    title: "Mountain View Ranch",
    price: "$250,000",
    area: "25 Acres",
    location: "Colorado, USA",
    description: "A serene ranch with beautiful mountain views, perfect for farming or a vacation home.",
    person: "4/5",
    payment: "Bank Transfer, Cash",
    image: "https://cdn.pixabay.com/photo/2024/12/28/03/39/field-9295186_640.jpg",
  },
  {
    id: 2,
    title: "Oceanfront Paradise",
    price: "$650,000",
    area: "25 Acres",
    location: "Malibu, California",
    description: "Luxurious oceanfront property with private beach access and panoramic views.",
    person: "2/5",
    payment: "Mortgage, Bank Transfer",
    image: "https://cdn.pixabay.com/photo/2024/12/28/03/39/field-9295186_640.jpg",
  },
  {
    id: 3,
    title: "Oceanfront Paradise",
    price: "$650,000",
    area: "25 Acres",
    location: "Malibu, California",
    description: "Identical listing with modern amenities and direct ocean access.",
    person: "3/5",
    payment: "Down Payment Available",
    image: "https://cdn.pixabay.com/photo/2024/12/28/03/39/field-9295186_640.jpg",
  },
  {
    id: 4,
    title: "Mountain View Ranch",
    price: "$250,000",
    area: "25 Acres",
    location: "Colorado, USA",
    description: "Duplicate ranch listing ideal for eco-resorts or agricultural use.",
    person: "1/5",
    payment: "Bank Transfer, Cash",
    image: "https://cdn.pixabay.com/photo/2015/06/19/21/24/avenue-815297_640.jpg",
  },
  {
    id: 5,
    title: "Oceanfront Paradise",
    price: "$650,000",
    area: "25 Acres",
    location: "Malibu, California",
    description: "A peaceful ocean getaway with palm trees and breeze.",
    person: "2/5",
    payment: "Down Payment Available",
    image: "https://cdn.pixabay.com/photo/2015/06/19/21/24/avenue-815297_640.jpg",
  },
  {
    id: 6,
    title: "Oceanfront Paradise",
    price: "$650,000",
    area: "25 Acres",
    location: "Malibu, California",
    description: "Prime location property for residential or investment purposes.",
    person: "4/5",
    payment: "Down Payment Available",
    image: "https://cdn.pixabay.com/photo/2022/04/15/07/58/sunset-7133867_640.jpg",
  },
];

